# Generated by Django 4.1.5 on 2023-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savat',
        ),
        migrations.AddField(
            model_name='user',
            name='savat',
            field=models.ManyToManyField(to='home.product'),
        ),
    ]
